<?php

use Behat\Behat\Tester\Exception\PendingException;
use Behat\Behat\Context\Context;
use Behat\Gherkin\Node\PyStringNode;
use Behat\Gherkin\Node\TableNode;

/**
 * Defines application features from the specific context.
 */
class ApiContext implements Context
{
    private $user;

    /**
     * @var UserEmailService
     */
    private $userService;

    /**
     * @var TokenGeneratorService
     */
    private $tokenService;

    /**
     * @var UserRepository
     */
    private $userRepository;

    /**
     * @var EmailService
     */
    private $emailService;

    private $registrationResponse;

    /**
     * Initializes context.
     *
     * Every scenario gets its own context instance.
     * You can also pass arbitrary arguments to the
     * context constructor through behat.yml.
     */
    public function __construct(
        EmailService $emailService,
        UserEmailService $userService,
        UserRepository $userRepository,
        TokenGeneratorService $tokenService
    )
    {
        $this->userService = $userService;
        $this->emailService = $emailService;
        $this->tokenService = $tokenService;
        $this->userRepository = $userRepository;
    }

    /**
     * @Given there is user information provided as json :jsonUser
     * @param string $jsonUser
     */
    public function thereIsUserInformationProvidedAsJson(string $jsonUser)
    {
        $this->user = json_decode($jsonUser);
    }

    /**
     * @Then Email should be a valid email address
     */
    public function emailShouldBeAValidEmailAddress()
    {
        PHPUnit\Framework\Assert::assertSame(
            $this->user->email,
            filter_var($this->user->email, FILTER_VALIDATE_EMAIL)
        );
    }

    /**
     * @Then Email should be a unique email address
     */
    public function emailShouldBeAUniqueEmailAddress()
    {
        $isUnique = $this->userService->isEmailUnique($this->user->email);

        PHPUnit\Framework\Assert::assertTrue($isUnique);
    }

    /**
     * @Then Password should be a minimum :length digit
     * @param int $length
     */
    public function passwordShouldBeAMinimumDigit(int $length)
    {
        PHPUnit\Framework\Assert::assertGreaterThanOrEqual(
            6,
            strlen($length)
        );
    }

    /**
     * @Then Token should be generated by provided user information
     */
    public function tokenShouldBeGeneratedByProvidedUserInformation()
    {
        $token = $this->tokenService->generate($this->user->email);

        PHPUnit\Framework\Assert::assertNotEmpty($token);
    }

    /**
     * @Then All information of the user should be saved to database
     */
    public function allInformationOfTheUserShouldBeSavedToDatabase()
    {
        $this->registrationResponse = $this->userRepository->save($this->user);
    }

    /**
     * @Then User should receive an e-mail notification that states that user has been successfully registered
     */
    public function userShouldReceiveAnEMailNotificationThatStatesThatUserHasBeenSuccessfullyRegistered()
    {
        $result = $this->emailService->send($this->emailService, "You have been registered successfully");

        PHPUnit\Framework\Assert::assertTrue($result);
    }

    /**
     * @Then I send a request to registration action
     */
    public function iSendARequestToRegistrationAction()
    {
        PHPUnit\Framework\Assert::assertNotNull($this->user);
    }

    /**
     * @Then System should return user Id and the Token after registration
     */
    public function systemShouldReturnUserIdAndTheTokenAfterRegistration()
    {
        PHPUnit\Framework\Assert::assertTrue(
            key_exists("id", $this->registrationResponse)
            && key_exists("token", $this->registrationResponse)
        );
        PHPUnit\Framework\Assert::assertNotEmpty($this->registrationResponse->id);
        PHPUnit\Framework\Assert::assertNotEmpty($this->registrationResponse->token);
    }
}