<?php

use App\Application\Utility\ContainerInjection;
use App\Domain\User\User;
use App\Domain\User\UserRepository;
use App\Service\EmailService;
use App\Service\TokenGeneratorService;
use App\Service\UserEmailService;
use Behat\Behat\Context\Context;
use Behat\Gherkin\Node\TableNode;

/**
 * Defines application features from the specific context.
 */
class DomainContext implements Context
{
    use ContainerInjection;

    /**
     * @var User
     */
    private $user;

    /**
     * @var EmailService
     */
    private $emailService;

    /**
     * @var UserEmailService
     */
    private $userService;

    /**
     * @var UserRepository
     */
    private $userRepository;

    /**
     * @var TokenGeneratorService
     */
    private $tokenService;

    /**
     * @var User
     */
    private $registrationResponse;

    /**
     * Initializes context.
     *
     * Every scenario gets its own context instance.
     * You can also pass arbitrary arguments to the
     * context constructor through behat.yml.
     */
    public function __construct()
    {
        $container = $this->getContainer();
        $this->emailService = $container->get(EmailService::class);
        $this->userService = $container->get(UserEmailService::class);
        $this->userRepository = $container->get(UserRepository::class);
        $this->tokenService = $container->get(TokenGeneratorService::class);
    }

    /**
     * @Given there is user information provided by visitor as a table:
     * @param TableNode $table
     */
    public function thereIsUserInformationProvidedByVisitorAsATable(TableNode $table)
    {
        // Get first row of table node
        $user = $table->getIterator()[0];
        $this->user = new User($user["email"], $user["password"]);
    }

    /**
     * @When I submit the form
     */
    public function iSubmitTheForm()
    {
        PHPUnit\Framework\Assert::assertNotNull($this->user);
    }

    /**
     * @Then Email should be a valid email address
     */
    public function emailShouldBeAValidEmailAddress()
    {
        PHPUnit\Framework\Assert::assertSame(
            $this->user->getEmail(),
            filter_var($this->user->getEmail(), FILTER_VALIDATE_EMAIL)
        );
    }

    /**
     * @Then Email should be a unique email address
     */
    public function emailShouldBeAUniqueEmailAddress()
    {
        $isUnique = $this->userService->isEmailUnique($this->user->getEmail());

        PHPUnit\Framework\Assert::assertTrue($isUnique);
    }

    /**
     * @Then Password should be a minimum :length digit
     * @param int $length
     */
    public function passwordShouldBeAMinimumDigit(int $length)
    {
        PHPUnit\Framework\Assert::assertGreaterThanOrEqual(
            6,
            strlen($length)
        );
    }

    /**
     * @Then Token should be generated by provided user information
     */
    public function tokenShouldBeGeneratedByProvidedUserInformation()
    {
        $token = $this->tokenService->generate($this->user->getEmail());

        PHPUnit\Framework\Assert::assertNotEmpty($token);
    }

    /**
     * @Then All information of the user should be saved to database
     */
    public function allInformationOfTheUserShouldBeSavedToDatabase()
    {
        $this->registrationResponse = $this->userRepository->save($this->user);
    }

    /**
     * @Then System should return user Id and the Token after registration
     */
    public function systemShouldReturnUserIdAndTheTokenAfterRegistration()
    {
        PHPUnit\Framework\Assert::assertNotEmpty($this->registrationResponse->getId());
        PHPUnit\Framework\Assert::assertNotEmpty($this->registrationResponse->getToken());
    }

    /**
     * @Then User should receive an e-mail notification that states that user has been successfully registered
     */
    public function userShouldReceiveAnEMailNotificationThatStatesThatUserHasBeenSuccessfullyRegistered()
    {
        $result = $this->emailService->send($this->emailService, "You have been registered successfully");

        PHPUnit\Framework\Assert::assertTrue($result);
    }
}
