Feature: User registration
  In order to register an account by a visitor
  As a visitor
  I should be able to register an account on the website

  Rules:
  - Id is unique
  - Email is unique
  - Token must be unique
  - Password is digit and its minimum length is 6

  @api
  Scenario: Sending user information as raw json body
    Given there is user information provided as json "{'email':'furkan@example.com', 'password': 123456 }"
    Then I send a request to registration action
    And Email should be a valid email address
    And Email should be a unique email address
    And Password should be a minimum 6 digit
    And Token should be generated by provided user information
    And All information of the user should be saved to database
    And System should return user Id and the Token after registration
    And User should receive an e-mail notification that states that user has been successfully registered

  @domain
  Scenario: Sending user information by filling registration form
    Given there is user information provied by visitor as a table:
      | Email              | Password |
      | furkan@example.com | 123456   |
    When I submit the form
    Then Email should be a valid email address
    And Email should be a unique email address
    And Password should be a minimum 6 digit
    And Token should be generated by provided user information
    And All information of the user should be saved to database
    And We should get Id and Token of the user who has been saved
    And User should receive an e-mail notification that states that user has been successfully registered